### ISSUE TITLE
Open Generic services don't work with anything but implementation types

### ISSUE THREAD

**Issue by davidfowl** [aspnet/DependencyInjection#257] opened 2015-07-12 08:48 UTC
The generic service registration assumes an implementation type and explodes with a null ref if one wasn't provided. We should either throw up front or support this in some way. Supporting an implementation factory would mean that the callback would need access to the closed generic.

/cc @lodejard

**Comment by muratg** [comment] 2015-07-14 17:28
@davidfowl isn't this by design? Do you mean null ref should be thrown earlier in the stack (at registration time, perhaps?)

**Comment by davidfowl** [comment] 2015-07-15 02:07
If it's by design then yes it needs to throw at registration time

**Comment by davidfowl** [comment] 2015-07-15 02:08
Or eve throw at resolve time

**Comment by ilmax** [comment] 2015-07-15 07:08
IMO it's ways better to throw at registration time than at resolve time, so if open generics aren't supported, please throw at registration time.

**Comment by muratg** [comment] 2015-07-28 20:44
@Eilon Could you reassign this?

**Closed** 2015-08-03 19:57 UTC
Labels: bug
