### ISSUE TITLE
The type 'IServiceProvider' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by soadyp** [aspnet/DependencyInjection#504] opened 2017-03-13 05:31 UTC
I am able to us  `ServiceProvider.AddTransient<IDbTools, DBTools>();`
BUT   `ServiceProvider.BuildServiceProvider(); `   returns the error

> Error	CS0012	The type 'IServiceProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ComponentModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.	

MS DI and System.ComponentModel have been referenced using  Nuget.
The project Targets UWP 10.0 Build 12393

```json
 "dependencies": {
    "Microsoft.EntityFrameworkCore.Sqlite": "1.1.1",
    "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.1.1",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0",
    "Microsoft.Extensions.DependencyInjection": "1.1.0",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.1.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.3.1",
    "NETStandard.Library": "1.6.0",
    "System.ComponentModel": "4.3.0",
    "System.ComponentModel.Annotations": "4.3.0",
    "System.ComponentModel.Primitives": "4.3.0",
    "System.ComponentModel.TypeConverter": "4.3.0"
  },
```

**Comment by muratg** [comment] 2017-04-14 22:46
@soadyp Did you find a solution to this yet? We'll investigate this if not.

**Comment by Eilon** [comment] 2017-06-08 21:02
Closing because there is not enough information to reproduce this problem.

**Closed by Eilon** 2017-06-08 21:02 UTC
