### ISSUE TITLE
ActivatorUtilities prefers default ctor over parameterful ctor

### ISSUE THREAD

**Issue by GrabYourPitchforks** [aspnet/DependencyInjection#197] opened 2015-03-05 06:33 UTC
Define a class with two constructor overloads:

`.ctor()`
`.ctor(IServiceProvider services)`

`ActivatorUtilities.CreateInstance` will call the parameterless ctor even though the parameterful ctor is a better match.

**Comment by Antaris** [comment] 2015-10-15 13:25
You say *better* match but that is your assumption because you understand the intent of your code, the ActivatorUtilities type doesn't. 

I think a better solution would be to review your code to understand why you have each constructor and if using ActivatorUtilities is the right way to go. 

Should you be resolving through the DI container instead using a component registration which says which constructor to use?

**Comment by khellang** [comment] 2015-11-12 08:49
According to @pakrym in https://github.com/aspnet/HttpAbstractions/pull/475, this shouldn't be an issue anymore?

**Comment by davidfowl** [comment] 2015-11-12 08:59
ctor injecton is fine, ActivatorUtilities is not.

/cc @pranavkm

**Comment by pranavkm** [comment] 2015-11-12 14:55
Yeah - the issue is that we cannot introspect what services are registered in a container without realizing it. That's too expensive to determine the best match.

**Comment by Eilon** [comment] 2016-01-23 01:28
Moving this to Backlog as we are not planning to make any changes for this at this time.

**Comment by divega** [comment] 2016-11-07 20:02
@Eilon @pranavkm can we consider assigning this to the 1.2 release? We have hit it multiple times and it seems to make more sense to have consistent behavior.

cc @anpete @bricelam @AndriySvyryd

**Comment by Eilon** [comment] 2016-11-07 21:17
@divega we can certainly consider it, but isn't it a breaking change?

Plus we'll need to look at the perf concern.

**Comment by divega** [comment] 2016-11-07 22:09
@Eilon I would suggest you let the user choose. The currently only choice maybe the fastest but it is less likely to satisfy the user's requirements and expectations.

**Comment by Eilon** [comment] 2016-11-07 22:33
So the suggestion is to add a flag to get the new behavior? That's certainly reasonable...

**Comment by divega** [comment] 2016-11-08 00:46
Yes, a flag on the methods that take a service provider is what I had in mind, although there might be bit of an explosion of methods with it.

**Comment by Antaris** [comment] 2016-11-09 08:26
@divega How would such a flag work, something like `[Preferred]` which the `ActivatorUtilities` type would look for?

**Comment by divega** [comment] 2016-11-09 11:25
@Antaris I will totally leave that to the DI folks. 

That said, what I had in mind was new methods or new overloads of the existing methods which take a bool or an enum (making sure the new parameter is not ambiguous with the params arguments) to control the behavior. 

What you say could be nice, but I would expect such attribute to play a role in selecting the constructor when instantiating a service (as opposed to only affecting `ActivatorUtilities`) and that is something I am not sure we would do if it only worked with our DI container.

**Comment by Eilon** [comment] 2016-11-27 06:35
See also: https://github.com/aspnet/DependencyInjection/issues/464

**Comment by Eilon** [comment] 2017-03-03 00:46
No plans to do this.

**Closed by Eilon** 2017-03-03 00:46 UTC
Labels: needs design, wontfix
