### ISSUE TITLE
Is there a better home for IContextAccessor<T> implementation?

### ISSUE THREAD

**Issue by loudej** [aspnet/DependencyInjection#49] opened 2014-03-19 05:23 UTC
Should interface be assembly neutral?
Should interface live in a carrier assembly?

**Comment by HaoK** [comment] 2015-03-09 04:22
This is a dupe of https://github.com/aspnet/DependencyInjection/issues/186 since ContextAccessor got renamed to IScopedInstance...

**Closed by HaoK** 2015-03-09 04:22 UTC
Labels: 0 - Backlog, 1 - Ready
