### ISSUE TITLE
Getting A New ApplicationDbContext

### ISSUE THREAD

**Issue by eriksendc** [aspnet/DependencyInjection#388] opened 2016-03-20 16:28 UTC
Hi All,

DbContext (and hence the default ApplicationDbContext DbContext that comes with an ASP.NET 5 template web application) is not thread safe. There are times when one wants to use Parallel.ForEach() and within it's lambda new up a db context (using a using block) so that you can parallelize a set of row-by-row database updates.

I've been trying to figure this out. I even tried injecting IServiceProvider into my constructor, but calling GetService on it keeps giving me the same instance of ApplicationDbContext. 

I need a way to create new instances of ApplicationDbContext. Any help would be greatly appreciated.

Thanks,
-Brian

**Comment by pranavkm** [comment] 2016-03-20 17:37
Sounds like a question for [EF](https://github.com/aspnet/EntityFramework)?

**Comment by eriksendc** [comment] 2016-03-20 18:16
I'm not sure that that's true. A plain old DbContext can definitely still be created using a using block. I thin this question should be fielded by whoever knows about the ApplicationDbContext that's a part of the ASP.NET web application template, mixed with someone who knows about DI in ASP.NET 5/Core...

**Comment by Eilon** [comment] 2016-03-23 17:28
@divega @HaoK this seems to be a question around this code: https://github.com/aspnet/Templates/blob/dev/src/Rules/StarterWeb/IndividualAuth/Startup.cs#L45-L46

**Comment by divega** [comment] 2016-03-23 23:20
It does sound like an EF question to me :smile:

> I need a way to create new instances of ApplicationDbContext

The `AddDbContext<TContext>()` method adds `TContext` as a scoped service, so if you resolved it in the same request from DI you will always get the same instance, and that is by design.

Although I am not sure it is a good idea to parallelize updates like you are describing, we do recognize that there are valid scenario for having multiple instance of a `DbContext` to be used in the same request, and this has been discussed in the EF repro. 


With RC1 bits and template this is a bit confusing and difficult, but for RC2 we have made a number of changes that will enable simply creating a new instance of the application's DbContext and passing the right DbContextOptions

**Comment by eriksendc** [comment] 2016-03-23 23:44
Thanks for your response @divega . I guess I'm assuming that this is more an ASP.NET concern than an EF one because I was guessing that the implementation details of ApplicationDbContext (extending IdentityDbContext<ApplicationUser>) and how it is all created by the template is not 'owned' by the EF team. Does the EF team own that? The way IdentityDbContext<ApplicationUser> is implemented it hides the ability to create a new instance of ApplicationDbContext directly (at least that's what I think I'm seeing). So I was considering this a concern of the ASP.NET team because of that. 

At the end of the day I just need help from the right team. Also, if you know for sure that my scenario is one that can be solved once we get to RC2, I'm cool with waiting for that.

Finally, I get your point about not wanting to willy nilly do things with parallelism and whatnot. But I'm confident that used sparingly and appropriately it's a tool in the toolbox that one should have when one needs. In the old world where we would "new up" db contexts via a using block, updates done to batches of rows via parallel.foreach could be done 10x to 20x faster than single threading.

Thanks for helping/listening.

-Brian Eriksen

**Comment by divega** [comment] 2016-03-23 23:48
I think what you see in the default template and ApplicationDbContext is mostly usage of patterns provided by EF, e.g. the `AddDbContext<TContext>()` method is defined in EF.

I actually hit the comment button too soon. Here is some more information:

* The ability to create multiple instances of a `DbContext in the same request is discussed here: https://github.com/aspnet/EntityFramework/issues/4441. 

* The changes we made post RC1 which simplify the patterns to create new instances are discussed here:
https://github.com/aspnet/EntityFramework/issues/4668.

I am actually now thinking that https://github.com/aspnet/EntityFramework/issues/4441 can now be closed because you can now just use `new` and pass the appropriate dependencies on the constructor whenever you need a new instance.

**Comment by divega** [comment] 2016-03-23 23:49
I am going to go ahead and close this issue because I am confident that I have responded to your question, but feel free to reactivate or to start a new thread in the EF repo.

**Closed by divega** 2016-03-23 23:49 UTC
