### ISSUE TITLE
[feature] Support `Func<IServiceProvider, Type, object> implementationFactory` ?

### ISSUE THREAD

**Issue by Cologler** [aspnet/DependencyInjection#588] opened 2017-10-05 12:10 UTC
Pass the service type into factory is useful.

**Comment by khellang** [comment] 2017-10-05 12:25
Dupe of https://github.com/aspnet/DependencyInjection/issues/498, related to https://github.com/aspnet/DependencyInjection/issues/474

**Closed** 2017-10-05 12:34 UTC
