### ISSUE TITLE
"Could not resolve service for type" on unreachable path

### ISSUE THREAD

**Issue by jaredcnance** [aspnet/DependencyInjection#514] opened 2017-04-13 21:17 UTC
**dotnet --version**: 1.0.0
**framework**: netcoreapp1.0

Suppose an app uses the following dependency chain:
```
Controller
|--Service<T>
|----Repository<T>
```

```csharp
public class MyModelsController
{
    public MyModelsController(IResourceService<MyModel> resourceService)
    { }
    // ...
}
```

And a library may be used to define some "default" services like so:

```csharp
services.AddScoped(typeof(IResourceService<>), typeof(EntityResourceService<>));
services.AddScoped(typeof(IEntityRepository<>), typeof(DefaultEntityRepository<>));
```

```csharp
public class EntityResourceService<T> : IResourceService<T> where T : class
{
  public EntityResourceService(IEntityRepository<T> entityRepository)
  {  }
  // ...
}
```

Now suppose the application injects a specific service that implements `IResourceService<MyModel>`. 

```csharp
services.AddDefaults(); // assume this is just the code above
services.AddScoped<IResourceService<MyModel>, MyModelService>();
```

```csharp
public class MyModelService : IResourceService<MyModel>
{
  MyModelService()
  { } 
  // ...
}
```

DI will resolve this more specific dependency instead of the unbound generic. However, it still checks the unbound generic dependency chain (dependencies of `EntityResourceService<>`). If `MyModelService` has no dependency on `IEntityRepository<>`, but `DefaultEntityRepository<>` has dependencies that are not in the container it will fail with 

>Unable to resolve service for type ... while attempting to activate ...DefaultEntityRepository

If the dependencies are added, it works, but resolves the `MyModelService ` not the `EntityResourceService<>`. Hopefully this makes sense.

**Comment by muratg** [comment] 2017-04-14 22:51
@pakrym Let's investigate for 2.0.0.

**Comment by pakrym** [comment] 2017-06-01 16:26
I'm not able to reproduce your issue, can you please provider a repro code that fails?

**Comment by pakrym** [comment] 2017-06-21 18:55
Closing, please reopen if you still see this issue.

**Closed by pakrym** 2017-06-21 18:55 UTC
Labels: 1 - Ready, bug
